export const FOCUS_DURATION_MINUTES = 25;
export const BREAK_DURATION_MINUTES = 5;


export const FOCUS_DURATION_MS = FOCUS_DURATION_MINUTES * 60 * 1000;
export const BREAK_DURATION_MS = BREAK_DURATION_MINUTES * 60 * 1000;